project:
  type: book

book:
  title: "rnpy"
  author: "Norah Jones"
  date: "07/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - shell_execution.qmd
    - environments.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

