project:
  type: book

book:
  title: "Combining R and Python for Scientific Computing"
  author: "Thomas Zwagerman"
  date: "07/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Python for the R User" 
      chapters: 
        - differences.qmd 
    - part: "Using R and Python Together"
      chapters:
        - bridges.qmd
        - language_agnostic_publishing.qmd
        - webapps_shiny.qmd
        - shell_execution.qmd
        - environments.qmd
    - summary.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

editor: visual

